name: 'Check submodules'

on:
  pull_request:

jobs:
  protobuf:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout code'
      uses: actions/checkout@v2
      with:
        path: assets/protobuf
        branch: dev
        fetch_depth: 50
